### PR TITLE
feat: allow multiple --src-statics options

### LINKED ISSUE #37: Feature request: Allow --src-statics multiple times
# Problem
Currently (sinnerschrader-website)[https://github.com/sinnerschrader/sinnerschrader-website] copies static resources into the working-copy to taint statics.
This leads to an always polluted/modified working-copy which is not easy to handle in git. Its even harder to resolve conflicts then.

It would be better if schlump itself is able to taint statics.

# Solution

If `--src-statics` could be given multiple times and order matters, then copying statics from all static folders in order would lead to the requried taining without changing the git working copy too much.

### PR DESCRIPTION
**Pull request by marionebl**
- use it by repeating --src-statics=[value]

closes #37

### CODE REVIEW

**Comment by KnisterPeter** [comment]
Please update the usage and README to reflect the option to give statics multiple times.

**Comment by KnisterPeter** [comment]
As well, why did you remove the big read 'FAILED' in case of an error?

**Comment by marionebl** [comment]
Missing "FAILED" prefix: sloppiness. Will adapt the PR, stay tuned.

**Comment by KnisterPeter** [comment]
Oh, just ignore my comment about missing FAILED output. It was collaped in the github commit diff.

**Comment by marionebl** [comment]
@KnisterPeter Could you change the coveralls settings? Don't want to trigger a failing master build.

**Comment by KnisterPeter** [comment]
Done. Settings are now 'allow decrease of coverage by 1%' and 'fail below 50%'.

**Pull request merged**
