### PR TITLE
feat: render scoped css

### PR DESCRIPTION
**Pull request by KnisterPeter**
Add posibility to render scoped css which is defined in the templates itself.
This is a bit like css-modules.

ISSUES CLOSED: #3

### CODE REVIEW

**Comment by KnisterPeter** [comment]
What do you think of this first draft?

**Comment by marionebl** [comment]
I like the look of it - will take it for a ride later today and check back here.

**Comment by marionebl** [comment]
Currently this

```
<style scoped>
	/* */
</style>
```

throws

```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at cssom.classNames.cssom.stylesheet.rules.reduce (~node_modules/schlump/src/components.js:48:33)
    at Array.reduce (native)
    at createScopedCss (~node_modules/schlump/src/components.js:47:4)
    at createReactComponent (~node_modules/schlump/src/components.js:65:29)
    at sander.readFile.then.content (~node_modules/schlump/src/components.js:29:7)
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at cssom.classNames.cssom.stylesheet.rules.reduce (~node_modules/schlump/src/components.js:48:33)
    at Array.reduce (native)
    at createScopedCss (~node_modules/schlump/src/components.js:47:4)
    at createReactComponent (~node_modules/schlump/src/components.js:65:29)
    at sander.readFile.then.content (~node_modules/schlump/src/components.js:29:7)
```

**Comment by KnisterPeter** [comment]
Fixed css comments

**Comment by marionebl** [comment]
I really like the limits to css selectors imposed by this approach, in a real-world scenario there are some things that would need to be added though:

1. Support a variable mechanism, or more general: shared information and/or context
2. `<input/>` based mechanics are impossible to implement because they rely on the sibling selectors: `+` and `~`.

**Comment by KnisterPeter** [comment]
I'll open new issues for the limitations. They do not block using this in cases where it works for now. Are you fine with that?

**Comment by marionebl** [comment]
For sure, go ahead.

**Pull request merged**
